# -*- coding: utf-8 -*-
"""Exercício14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRQBY8iz73UfjgJQzYBurkDRj2k_zNRG

**14) Faça um programa para imprimir os números pares de 100 à 50.**
"""

i = 100
while i >= 50:
  if i % 2 == 0:
    print(i)  
  i -= 1