# -*- coding: utf-8 -*-
"""Exercício8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1YRQVjfSvnLDapWNPZ1TdbbN1PZ6Pf4

**8) Faça um programa para ler 10 números inteiros e imprimir a soma dos números que são ímpares.**
"""

i = 0
soma = 0

while i < 10:
  num = int(input('Digite um número: '))
  if num % 2 != 0:
    soma += num

  i += 1
print('Soma dos números ímpares: ',soma)