# -*- coding: utf-8 -*-
"""Exercício1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AYdGGHZTxVxfSQrPhJMgZi6D0fSPujXq

**1) Faça um programa para calcular e apresentar o valor do volume de uma lata de óleo, utilizando a fórmula: Volume = PI x R2 x H. Onde R é o raio e H a altura da lata.**
"""

h = float(input("Digite a altura: "))
r = float(input("Digite o raio: "))
volume = 3.14 * (r**2)  * h

print('O volune da lata de óleo é de {:.2f}'.format(volume))