# -*- coding: utf-8 -*-
"""Exercício7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdPlkn8nHIRERsINQXtE2PCv0JT7LwAO

**7) Escreva um programa que receba 5 notas de provas e imprima as médias das notas**
"""

i = 0
soma = 0

while i < 5:
  nota = float(input('Entre com o valor da nota: '))
  soma += nota
  if nota > 10 or nota < 0:
    print('NOTA INCORRETA')
  else:
    media = soma / 5
  
  i += 1

print('Média: ', media)