# -*- coding: utf-8 -*-
"""Exercício5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152fa2KcLvhfktdvdw8bYxMfBU6yRWLUL

**5) Sabendo que o latão é obtido fundindo-se sete partes de cobre com três partes de zinco, faça um programa que solicite quantos quilos de latão se quer produzir e imprima quantos quilos de cobre e zinco são necessários.**
"""

qtd_desejada = int(input('Quantos litros tem o latão? '))

cobre_necessario = qtd_desejada * 0.7
zinco_necessario = qtd_desejada * 0.3

print(cobre_necessario,'litros de cobre e ', zinco_necessario,'litros de zinco')