# -*- coding: utf-8 -*-
"""Exercício13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHhF_s4fMTx1qUsStmM2LnEk97YMhPAM

**13) Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.**
"""

for i in range(1,21):
  print('{}'.format(i))

print('\n')
for i in range(1,21):
  print(i, end=' ' )