# -*- coding: utf-8 -*-
"""Exercício3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCr1tWssdYV55WOlO9ySGTSuRK9lJTaH

**3) Faça um programa para ler um valor real e apresentar este valor com desconto de 10%.**
"""

valorreal = float(input("Digite o valor da compra: "))
desconto = 0.1

valorfinal = valorreal - (valorreal * desconto)
print("Tendo o valor de 10% de desconto")
print("\nO valor da compra com o desconto é: R$", valorfinal)