# -*- coding: utf-8 -*-
"""Exercício12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWPCySuCO6aV4Yj1myXnNujd-hg-w420

**12) Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.**
"""

valorinicio = int(input('Entre com o primeiro valor: '))
valorfinal = int(input('Entre com o segundo valor: '))

for i in range(valorinicio + 1, valorfinal):
  print(i)