# -*- coding: utf-8 -*-
"""Exercício10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yd8VtCEJnum6HmRFbmcPqoFOEurYmO4c

**10) Faça um programa para calcular o fatorial de um valor N inserido pelo usuário.**
"""

N = int(input('Informe o valor de N: '))
fatorial = 1

while N >= 1:
  fatorial *= N
  N -= 1      

print(fatorial)