# -*- coding: utf-8 -*-
"""Exercício4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11R92fGQq073TZ2WY9c1-YxUWVEstC9Gx

**4) A fábrica de refrigerantes Meia Cola vende seu produto em 3 formatos: lata 355ml, garrafa de 290ml e garrafa de 2l. Se um comerciante compra um certa quantidade de cada formato, faça um programa para calcular quantos litros ele comprou no total.**
"""

print('Somos a Meia Cola e temos: \n\t Lata de 355ml \n\t Garrafa de 290ml \n\t Garrafa de 2l')

qtd1 = float(input("\nLatas de 355ml: "))
qtd2 = float(input("Garrafa de 290ml: "))
qtd3 = float(input("Garrafa de 2L: "))

ml = (qtd1*355) + (qtd2*290) + (qtd3*2000) 
litro = ml / 1000
print("Quantidade de Litros de Coca-Cola: {:.2f}".format(litro))