# -*- coding: utf-8 -*-
"""Exercício2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15x19JK5zNerr2zs-P4MamZ0i3K5O1v_C

**2) Faça um programa para ler dois valores (variáveis A e B) e efetuar as operações de adição, subtração, multiplicação e divisão de A por B, apresentado os quatro resultados obtidos**
"""

a = float(input("\nDigite o primeiro valor: "))
b = float(input("Digite o segundo valor: "))

soma = a + b
subt = a - b
mult = a * b
div = a / b

print("\nSoma:",soma)
print("Subtração:",subt)
print("Multiplicação:", mult)
print("Divisão:",div)