# -*- coding: utf-8 -*-
"""Exercício11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fElHbmyhflJ2-KaruDQg_pHU5UzSnQTB

**11) Faça um Programa que peça a idade e a altura de 5 pessoas, armazene cada informação no seu respectivo vetor, ou seja, um vetor para IDADE e um vetor para ALTURA. Imprima a idade e a altura de cada pessoa.**
"""

import numpy
idade = numpy.zeros((5), dtype=int)
altura = numpy.zeros(5)

print('Entre com a idade de 5 usuários: ')
for i in range(5):
  idade[i] = int(input('Idade: '))

print('\nEntre com a altura de 5 usuários: ')
for i in range(5):
  altura[i] = float(input('Altura: '))

print('\n')
for i in range(5):
  print('Idade: ', idade[i], end='   ') 
  print('Altura: {:.2f}'.format(altura[i]))